### ISSUE TITLE
Babel error after updating Next.js and React

### ISSUE THREAD

**Issue by dmt-13** [styled-components/styled-components#1210]
## Version
styled-components - 2.2.0
babel-plugin-styled-components - 1.2.1
Next.js - 4.0.0beta3
React & React.Dom - 16.0.0

My project uses Material-UI, styled-components and Next.js Everything was fine until I decided to update Next.js to beta version in order to start using React 16. After that I started to receive errors from my styled-components if I use interpolation inside (${}, like processing props, media queries, etc). Let's say this is my component: 

```
const Button = styled.button`
  font-size: 12px;
  color: ${props => props.primary ? 'white' : 'palevioletred'};
`;
```

In this case I'll get an error (see below). But If I remove color property, everything will be fine. Do you have any ideas what can cause this error? If needed, I can provide more information about the project. Thanks in advance!

Error:
```
Module build failed: TypeError: /path/to/projectsrc/components/Button.js: Property body[1] of BlockStatement expected node to be of a type ["Statement"] but instead got "CallExpression"
    at validate (/path/to/projectnode_modules/babel-types/lib/definitions/index.js:109:13)
    at validator (/path/to/projectnode_modules/babel-types/lib/definitions/index.js:57:7)
    at Object.validate (/path/to/projectnode_modules/babel-types/lib/definitions/index.js:190:10)
    at validate (/path/to/projectnode_modules/babel-types/lib/index.js:505:9)
    at Object.builder (/path/to/projectnode_modules/babel-types/lib/index.js:466:7)
    at NodePath.replaceExpressionWithStatements (/path/to/projectnode_modules/babel-traverse/lib/path/replacement.js:206:54)
    at NodePath.insertBefore (/path/to/projectnode_modules/babel-traverse/lib/path/modification.js:52:10)
    at processTaggedTemplateExpression (/path/to/projectnode_modules/styled-jsx/dist/babel-external.js:91:16)
    at PluginPass.TaggedTemplateExpression (/path/to/projectnode_modules/styled-jsx/dist/babel-external.js:122:5)
    at newFn (/path/to/projectnode_modules/babel-traverse/lib/visitors.js:276:21)
```

P.S. I cannot reproduce this problem with the fresh project that contains Next.js, React and styled-components. 
Here is my .babelrc file:

```
{
  "presets": ["next/babel", "flow"],
  "plugins": [
    ["babel-plugin-root-import"],
    [
      "babel-plugin-styled-components",
      {
        "ssr": true
      }
    ]
  ],
  "retainLines": true
}

```

**Comment by mxstbr** [comment]
This is likely an issue with the beta version of Next and not with styled-components since it doesn't happen on a new project, so I'll close this out. I'd recommend submitting an issue over in the Next repo!

/cc @arunoda

**Comment by philpl** [comment]
The error seems to hint at it being a styled-jsx bug:

> at processTaggedTemplateExpression (/path/to/projectnode_modules/styled-jsx/dist/babel-external.js:91:16)
> at PluginPass.TaggedTemplateExpression (/path/to/projectnode_modules/styled-jsx/dist/babel-external.js:122:5)
