### ISSUE TITLE
TypeError: css.apply is not a function from constructWithOptions.js

### ISSUE THREAD

**Issue by slipperypenguin** [styled-components/styled-components#1344]
Hello, I'm using `styled-components` in a file that is causing my Jest tests to fail. The tests pass when the component that is using `styled-components` is removed and the error I'm receiving from Jest traces back to a file inside the `styled-components` node_module. Everything seems to work fine outside of the tests.

## Version
styled-components: 2.2.4,
babel-plugin-styled-components: 1.3.0
babel-jest: 21.2.0,
enzyme: 3.2.0,
jest: 21.2.1,

## Reproduction
I've tried to include the relevant files that seem to be causing the issue. If other files are needed that I haven't included here, just let me know and I'll get that over!

Example-test.js
```js
/**
 * @jest-environment jsdom
 */
/* eslint-disable function-paren-newline */

import React from 'react';
import NavMenu from '../../src/components/NavMenu';
import SubmitRequestLayer from '../../src/components/SubmitRequestLayer';
import { shallow, configure } from 'enzyme';

import Adapter from 'enzyme-adapter-react-16';

configure({ adapter: new Adapter() });

const testUserInfo = {
  _id: 'test.user@gmail.com',
  _rev: '1-f9f5fc9fed2ba996a3f3b2ff4e89fc2c',
  emailAddress: 'test.user@gmail.com',
  firstName: 'Test',
  lastName: 'User',
  uid: '123456789',
  role: 'Manager',
  permissions: {
    EDIT_EXP_DATA: true,
    EDIT_PERMISSIONS: true,
    VIEW_ONLY: false,
    RESTRICTED: false
  }
};

const constantDate = new Date('2017-06-13T04:41:20');

/* eslint no-global-assign:off */
Date = class extends Date {
  constructor() {
    super();
    return constantDate;
  }
};


describe('Test that NavMenu and child components render', () => {
  test('NavMenu renders', () => {
    const showTrue = shallow(<NavMenu userInfo={testUserInfo} currentPage='pdf' />);
    expect(showTrue).toMatchSnapshot();

    testUserInfo.permissions.EDIT_PERMISSIONS = false;
    const showFalse = shallow(<NavMenu userInfo={testUserInfo} currentPage='notes' />);
    expect(showFalse).toMatchSnapshot();
  });

  test('SubmitRequestLayer renders', () => {
    const component = shallow(<SubmitRequestLayer userInfo={testUserInfo} onClose={() => {}} />);
    expect(component).toMatchSnapshot();
  });
});

```

The file that contains `styled-components`:
Box.jsx

```js
import styled from 'styled-components';

const Box = styled.div`
  padding: ${props => props.pad};
  margin: ${props => props.margin};
  display: ${props => (props.notFlex ? null : 'flex')};
  align-items: ${props => props.alignItems};
  align-self: ${props => props.alignSelf};
  background: ${props => props.color || props.theme.box};
  justify-content: ${props => props.justifyContent};
  width: ${props => props.width};
  max-width: ${props => props.maxWidth};
  height: ${props => props.height};
  font: ${props => props.fontSize};
  overflow-y: ${props => (props.scrollY ? 'scroll' : 'visible')};
  float: ${props => props.float};
  box-shadow: ${props => (props.shadow ? `0px 1px 2px 0 ${props.theme.shadow}` : null)};
  &:hover {
    cursor: ${props => (props.pointer ? 'pointer' : null)};
  }
`;

export default Box;
```

## Steps to reproduce
The function in question that seems to be causing an issue ( from `node_modules/styled-components/lib/constructors/constructWithOptions.js` lines 20 - 27)
```js
/* This is callable directly as a template function */
    var templateFunction = function templateFunction(strings) {
      for (var _len = arguments.length, interpolations = Array(_len > 1 ? _len - 1 : 0), _key = 1; _key < _len; _key++) {
        interpolations[_key - 1] = arguments[_key];
      }

      return componentConstructor(tag, options, css.apply(undefined, [strings].concat(interpolations)));
    };
```

## Expected Behavior
Expecting the Jest tests to pass, since they pass if the div from `Box.jsx` is removed from other components.

## Actual Behavior
The failing log from Jest:

```bash
 FAIL  __tests__/src/NavMenu.test.js
  ● Test suite failed to run

    TypeError: css.apply is not a function
      
      at Function.templateFunction [as div] (node_modules/styled-components/lib/constructors/constructWithOptions.js:26:53)
      at Object.<anonymous> (src/components/Box/Box.jsx:3:52)
      at Object.<anonymous> (src/components/EditorLayer/EditorLayer.jsx:6:12)
      at Object.<anonymous> (src/components/SubmitRequestLayer/SubmitRequestLayer.jsx:3:20)
      at Object.<anonymous> (src/components/NavMenu/NavMenu.jsx:5:27)
      at Object.<anonymous> (__tests__/src/NavMenu.test.js:7:16)
          at Generator.next (<anonymous>)
          at new Promise (<anonymous>)
          at Generator.next (<anonymous>)
          at <anonymous>

Test Suites: 1 failed, 2 passed, 3 total
Tests:       25 passed, 25 total
Snapshots:   0 total
Time:        3.411s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

Screenshot of the same test result:
![screen shot 2017-12-05 at 4 46 17 pm](https://user-images.githubusercontent.com/3655354/33632543-eeab8942-d9db-11e7-9a01-035e775b5c4f.png)

**Comment by slipperypenguin** [comment]
## An update on this:
I've managed to recreate this error using a basic setup through [create-react-app](https://github.com/facebookincubator/create-react-app) and have attached the setup below.

### File Setup
**package.json**
```json
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "jest",
    "test-cra": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-scripts": "1.0.17",
    "styled-components": "^2.2.4"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-plugin-styled-components": "^1.3.0",
    "enzyme": "^3.2.0",
    "enzyme-adapter-react-16": "^1.1.0",
    "enzyme-to-json": "^3.2.2",
    "jest": "^21.2.1",
    "jest-cli": "^21.2.1",
    "raf": "^3.4.0"
  },
  "jest": {
    "setupFiles": [
      "raf/polyfill"
    ],
    "moduleNameMapper": {
      ".*css$": "<rootDir>/__mocks__/mockCSS.css",
      ".*svg$": "<rootDir>/__mocks__/mockSVG.svg",
      ".*png$": "<rootDir>/__mocks__/mockPNG.png"
    },
    "snapshotSerializers": [
      "enzyme-to-json/serializer"
    ]
  }
}
```

**.babelrc**
```json
{
  "presets": [ "es2015", "react" ],
  "plugins": ["babel-plugin-styled-components"]
}
```

**App.js**
```javascript
import React, { Component } from 'react';
import styled from 'styled-components';
import logo from './logo.svg';
import './App.css';


const Button = styled.button`
  background: ${props => props.primary ? 'palevioletred' : 'white'};
  color: ${props => props.primary ? 'white' : 'palevioletred'};

  font-size: 1em;
  margin: 1em;
  padding: 0.25em 1em;
  border: 2px solid palevioletred;
  border-radius: 3px;
`;

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
        <div>
          <Button>Normal</Button>
		      <Button primary>Primary</Button>
        </div>
      </div>
    );
  }
}

export default App;
```

**App.test.js**
```javascript
/**
 * @jest-environment jsdom
 */

import React from 'react';
import ReactDOM from 'react-dom';
import App from '../src/App.js';
import { shallow, configure } from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';

configure({ adapter: new Adapter() });


describe('Test that Button components render', () => {
  test('Normal Button renders', () => {
    const buttonNorm = shallow(<Button />);
    expect(buttonNorm).toMatchSnapshot();
  });

  test('Primary Button renders', () => {
    const buttonPrim = shallow(<Button primary />);
    expect(buttonPrim).toMatchSnapshot();
  });
});

```

**Comment by philpl** [comment]
@slipperypenguin since you already have a CRA with the reproduction, can you please publish a repo or sth similar so we can just test and debug it :)

That’d save us a lot of time since most likely we won’t be able to spot anything here from just reading the code. Cheers! :)

**Comment by slipperypenguin** [comment]
@philpl Actually just figured out a solution [here](https://facebook.github.io/jest/docs/en/webpack.html#mocking-css-modules)

Looks like it was an issue with mocking css modules in Jest. 
In `package.json`:

### Old Setup
```json
"jest": {
    "setupFiles": [
      "raf/polyfill"
    ],
    "moduleNameMapper": {
      ".*css$": "<rootDir>/__mocks__/mockCSS.css",
      ".*svg$": "<rootDir>/__mocks__/mockSVG.svg",
      ".*png$": "<rootDir>/__mocks__/mockPNG.png"
    },
    "snapshotSerializers": [
      "enzyme-to-json/serializer"
    ]
  }
```

### New Setup
```json
"jest": {
    "setupFiles": [
      "raf/polyfill"
    ],
    "moduleNameMapper": {
      "\\.(jpg|jpeg|png|svg)$": "<rootDir>/__mocks__/fileMock.js",
      "\\.(css|less)$": "identity-obj-proxy"
    },
    "snapshotSerializers": [
      "enzyme-to-json/serializer"
    ]
  }
```
