### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by secreter** [styled-components/styled-components#1625]
I have something wrong.I write a demo likes this.
```javascript
const React = require("react")
const styled = require("styled-components")

let Box = styled.div`
  background: #985;
`
let Todo = () => <Box>hello</Box>
```

```javascript
const babelConfig = {
  presets: ["@babel/preset-env"],
  plugins: [
    "transform-react-jsx",
    [
      "babel-plugin-styled-components",
      {
        ssr: true
      }
    ]
  ]
}
const transformJsxToJs = function(jsx) {
  try {
    return transform(jsx, babelConfig).code
  } catch (e) {
    console.error("transformJsxToJs:", e)
    return ""
  }
}
```
and then I get the error massage
```
transformJsxToJs: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.extname (path.js:918:5)
    at getBlockName (F:\nodeitem\ssr-service\node_modules\babel-plugin-styled-components\lib\visitors\displayNameAndId.js:53:73)
    at getDisplayName (F:\nodeitem\ssr-service\node_modules\babel-plugin-styled-components\lib\visitors\displayNameAndId.js:62:21)
    at exports.default (F:\nodeitem\ssr-service\node_modules\babel-plugin-styled-components\lib\visitors\displayNameAndId.js:130:62)
    at PluginPass.TaggedTemplateExpression (F:\nodeitem\ssr-service\node_modules\babel-plugin-styled-components\lib\index.js:21:40)
    at newFn (F:\nodeitem\ssr-service\node_modules\@babel\traverse\lib\visitors.js:223:21)
    at NodePath._call (F:\nodeitem\ssr-service\node_modules\@babel\traverse\lib\path\context.js:64:19)
    at NodePath.call (F:\nodeitem\ssr-service\node_modules\@babel\traverse\lib\path\context.js:38:17)
    at NodePath.visit (F:\nodeitem\ssr-service\node_modules\@babel\traverse\lib\path\context.js:99:12)
```

**Comment by kitten** [comment]
This is indeed a little weird, however I’ll need to ask for a reproduction please :)

The general reasoning here is, time that we spent on reproductions is essentially wasted and could be spent on something else, be it for styled-components or not. Since whether you can reproduce this bug is a big part of if it’s a usage error or not, that already saves us from some false positives

Cheers :)
