### ISSUE TITLE
Error: Could not parse CSS stylesheet on Jest 23.5.0

### ISSUE THREAD

**Issue by Sly777** [styled-components/styled-components#1931]
I found a weird error (it's possibly related to JSDOM but I opened the issue on here because I'm getting an error on styled-component comp only). My tests were working with **Jest 20.0.4**, but It's started to give an error like "Error: Could not parse CSS stylesheet" after I updated to **Jest 23.5.0**. And after update, Only I started to get this error somehow, everything else is working. Also I didn't change anything on jest setup after the update. (maybe I should :)

## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
 - Memory: 659.29 MB / 16.00 GB
 - Shell: 5.5.1 - /usr/local/bin/zsh
## Binaries:
 - Node: 8.11.2 - ~/.nvm/versions/node/v8.11.2/bin/node
 - Yarn: 1.9.4 - /usr/local/bin/yarn
 - npm: 5.6.0 - ~/.nvm/versions/node/v8.11.2/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.5.1 => 1.5.1 
 - styled-components: 3.4.2 => 3.4.2 
## Other Packages:
 - "enzyme": "^3.4.4"
 - "babel-jest": "^23.4.2"
 - "jest": "^23.5.0"
 - "jest-styled-components": "^6.1.0"

## Example Error
```
Error: Could not parse CSS stylesheet
          at exports.createStylesheet (/Users/x/x/x/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:35:21)
          at HTMLStyleElementImpl._updateAStyleBlock (/Users/x/x/x/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:67:5)
          at HTMLStyleElementImpl._childTextContentChangeSteps (/Users/x/x/x/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:36:12)
          at TextImpl.replaceData (/Users/x/x/x/node_modules/jsdom/lib/jsdom/living/nodes/CharacterData-impl.js:73:23)
          at TextImpl.appendData (/Users/x/x/x/node_modules/jsdom/lib/jsdom/living/nodes/CharacterData-impl.js:43:10)
          at Text.appendData (/Users/x/x/x/node_modules/jsdom/lib/jsdom/living/generated/CharacterData.js:76:21)
          at Object.insertRules (/Users/x/x/x/node_modules/styled-components/dist/styled-components.cjs.js:734:16)
          at StyleSheet.inject (/Users/x/x/x/node_modules/styled-components/dist/styled-components.cjs.js:1174:11)
          at ComponentStyle.generateAndInjectStyles (/Users/x/x/x/node_modules/styled-components/dist/styled-components.cjs.js:2070:20)
          at StyledComponent.generateAndInjectStyles (/Users/x/x/x/node_modules/styled-components/dist/styled-components.cjs.js:1752:38) 
      /* sc-component-id: sc-bMVAic */
      
      /* sc-component-id: sc-bAeIUo */
      
      /* sc-component-id: sc-iujRgT */
      
      /* sc-component-id: sc-GMQeP */
      
      /* sc-component-id: sc-exAgwC */
      
      /* sc-component-id: sc-cQFLBn */
      
      /* sc-component-id: sc-gojNiO */
      
      /* sc-component-id: sc-daURTG */
      
      /* sc-component-id: sc-bXGyLb */
      
      /* sc-component-id: sc-lkqHmb */
      
      /* sc-component-id: sc-eLExRp */
      
      /* sc-component-id: sc-cbkKFq */
      
      /* sc-component-id: sc-krvtoX */
      
      /* sc-component-id: sc-fYiAbW */
      
      /* sc-component-id: sc-fOKMvo */
      
      /* sc-component-id: sc-dUjcNx */
      .sc-dUjcNx {} .iXdcVN{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex-wrap:wrap;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-box-pack:justify;-webkit-justify-content:space-between;-ms-flex-pack:justify;justify-content:space-between;width:100%;margin-top:0;margin-right:auto;margin-bottom:0;margin-left:auto;z-index:20;-webkit-box-pack:start;-webkit-justify-content:flex-start;-ms-flex-pack:start;justify-content:flex-start;background-color:#00cea5;-webkit-transform:translate3d(0,100%,0);-ms-transform:translate3d(0,100%,0);transform:translate3d(0,100%,0);-webkit-transition:-webkit-transform 0.5s ease-in 0.7s;-webkit-transition:transform 0.5s ease-in 0.7s;transition:transform 0.5s ease-in 0.7s;position:fixed;right:0;bottom:0;left:0;padding-top:4px;padding-bottom:4px;} @media (min-width:768px){.iXdcVN{position:relative;z-index:auto;background-color:#fff;-webkit-transform:none;-ms-transform:none;transform:none;-webkit-transition:none;transition:none;}} @media (min-width:1024px){.iXdcVN{margin-top:24px;}}
      /* sc-component-id: sc-gHboQg */
      .sc-gHboQg {} .rbjqa{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-pack:center;-webkit-justify-content:center;-ms-flex-pack:center;justify-content:center;width:calc(50% - 8px);} @media (min-width:768px){.rbjqa{width:100%;}} @media (min-width:1024px){.rbjqa{width:136px;margin-right:16px;}} @media (min-width:1280px){.rbjqa{width:100%;margin-right:0;}} @media (min-width:768px){.rbjqa:first-child{margin-bottom:12px;}} @media (min-width:768px){.rbjqa:last-child{margin-right:0;}} .rbjqa > i{display:inline-block;font-size:24px;position:relative;top:0;margin-right:12px;}
      /* sc-component-id: sc-eilVRo */
      
      /* sc-component-id: sc-eerKOB */
      
      /* sc-component-id: sc-emmjRN */
      
      /* sc-component-id: sc-cpmLhU */
      
      /* sc-component-id: sc-dymIpo */
      .sc-dymIpo {} .cQYZGZ{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:flex-start;-webkit-box-align:flex-start;-ms-flex-align:flex-start;align-items:flex-start;margin-right:-8px;margin-left:-8px;} @media (min-width:768px){.cQYZGZ{margin-right:-16px;margin-left:-16px;}}
      /* sc-component-id: sc-bnXvFD */
      .sc-bnXvFD {} .iobjvF{width:100%;} @media (min-width:1024px){.iobjvF{width:66.66666666666667%;}}
      /* sc-component-id: sc-gFaPwZ */
      .sc-gFaPwZ {} .cAIjGr{display:none;background-color:#fff;width:100%;} @media (min-width:1024px){.cAIjGr{display:block;padding-left:16px;width:33.333333333333336%;position:fixed;}@supports (display:grid){.cAIjGr{z-index:auto;position:-webkit-sticky;position:sticky;top:128px;}}} @media (min-width:1440px){.cAIjGr{padding-right:64px;padding-left:48px;}}
      /* sc-component-id: sc-fhYwyz */
      
      /* sc-component-id: sc-jzgbtB */
      
      /* sc-component-id: sc-gJWqzi */
      .sc-gJWqzi {}.cDUPZJ{position:fixed;overflow:hidden;width:100vw;}
      /* sc-component-id: sc-rBLzX */
      .sc-rBLzX {} .dfXXQM{margin-top:80px;} @media (min-width:768px){.dfXXQM{margin-top:88px;}} @media (min-width:1024px){.dfXXQM{margin-top:80px;}} @media (min-width:1280px){.dfXXQM{margin-top:80px;}}
      /* sc-component-id: sc-bMvGRv */
      .sc-bMvGRv {} .hyyzHE{display:block;padding:8px 16px;margin:0 auto 128px;} @include media(md){margin-bottom:256px;}/*|*/}
      /* sc-component-id: sc-CtfFt */
      .sc-CtfFt {} .hnKlrv{position:relative;z-index:10;width:100%;padding-top:42px;background-color:#f5f7f8;}
      /* sc-component-id: sc-laTMn */
      
      /* sc-component-id: sc-hGoxap */
      .sc-hGoxap {} .iQucSI{margin-left:7px;vertical-align:super;}
      /* sc-component-id: sc-fjmCvl */
      .sc-fjmCvl {} .cJvEzt{display:inline-block;}
      /* sc-component-id: sc-TFwJa */
      .sc-TFwJa {} .byFiTK{display:block;-webkit-flex:0 1 auto;-ms-flex:0 1 auto;flex:0 1 auto;-webkit-align-self:auto;-ms-flex-item-align:auto;align-self:auto;-webkit-order:0;-ms-flex-order:0;order:0;padding-right:8px;padding-left:8px;width:auto;padding-right:16px;padding-left:16px;} @media (min-width:768px){.byFiTK{padding-right:16px;padding-left:16px;}} .byFiTK > a,.byFiTK > span,.byFiTK > .sc-fjmCvl{display:inline-block;font-size:12px;color:#002937;cursor:pointer;}
      /* sc-component-id: sc-bHwgHz */
      .sc-bHwgHz {} .ivRzJo{font-size:21px;cursor:pointer;}
      /* sc-component-id: sc-krDsej */
      .sc-krDsej {} .iksgpG{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex-flow:column nowrap;-ms-flex-flow:column nowrap;flex-flow:column nowrap;-webkit-align-content:stretch;-ms-flex-line-pack:stretch;align-content:stretch;-webkit-align-items:flex-start;-webkit-box-align:flex-start;-ms-flex-align:flex-start;align-items:flex-start;-webkit-box-pack:start;-webkit-justify-content:flex-start;-ms-flex-pack:start;justify-content:flex-start;margin-right:-8px;margin-left:-8px;margin-right:-8px;margin-left:-8px;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row;margin-bottom:16px;} @media (min-width:768px){.iksgpG{-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row;}} @media (min-width:768px){.iksgpG{margin-right:-16px;margin-left:-16px;}} .iksgpG > .sc-gGBfsJ{width:100%;} .iksgpG::after{clear:both;} .iksgpG::before,.iksgpG::after{display:table;content:' ';} .iksgpG > .sc-TFwJa{position:relative;border-left:1px solid #d9dbdf;} .iksgpG > .sc-TFwJa:first-child{-webkit-flex:1 1 auto;-ms-flex:1 1 auto;flex:1 1 auto;padding-left:8px;border-left:none;} @media (min-width:768px){.iksgpG > .sc-TFwJa:first-child{-webkit-flex:0 1 auto;-ms-flex:0 1 auto;flex:0 1 auto;padding-left:16px;}} .iksgpG > .sc-TFwJa:last-child{padding-right:8px;} @media (min-width:768px){.iksgpG > .sc-TFwJa:last-child{padding-right:16px;}}
      /* sc-component-id: sc-dTdPqK */
      .sc-dTdPqK {} .kjVfce{font-size:21px;cursor:pointer;} .kjVfce.if-icon-mail{color:#000;} .kjVfce.if-icon-facebook{color:#3c5a99;} .kjVfce.if-icon-twitter{color:#1da1f2;}
      /* sc-component-id: sc-itybZL */
      .sc-itybZL {} .jwgstf{position:absolute;z-index:1060;top:45px;right:5px;min-width:170px;border:1px solid #d9dbdf;border-radius:4px;background-color:#fff;font-size:14px;opacity:0;pointer-events:none;-webkit-transition:opacity 0.2s ease-in;transition:opacity 0.2s ease-in;} .jwgstf > ul{padding:0;margin:0;list-style:none;} @media (min-width:768px){.jwgstf{right:auto;left:5px;}}
      /* sc-component-id: sc-eMigcr */
      .sc-eMigcr {} .kQWyXZ{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;padding:19px 12px;color:#000;cursor:pointer;} .kQWyXZ:hover{color:#00cea5;} .kQWyXZ > .sc-dTdPqK{display:inline-block;min-width:21px;margin-right:14px;}
      /* sc-component-id: sc-fzsDOv */

```

**Comment by probablyup** [comment]
Sounds like the JSDOM update has some sort of incompatibility in their fake stylesheet API.  Not sure what can be done on our end... you can switch the version of JSDOM you’re using in jest though.

**Comment by probablyup** [comment]
I’d double check your styles for any syntax errors though.

**Comment by glennflanagan** [comment]
For anyone looking for this error I found that it was a multiline CSS comment inside a `css` call from `styled-components` that caused this issue. Specifically my CSS reset.

```
import { css } from 'styled-components';

export default css`
  /*!
  * ress.css • v1.2.2
  * MIT License
  * github.com/filipelinhares/ress
  */
```

Changing the comment to individual single-line comments fixed it for me.

```
import { css } from 'styled-components';

export default css`
  //
  // ress.css • v1.2.2
  // MIT License
  // github.com/filipelinhares/ress
  //
```

**Comment by feugy** [comment]
I had the same issue. Forcing the use of a more recent version of js-dom did not fixed it: I had to remove multiline comments from all my (external) style sheets.

@probablyup, for information, this issue came with styled-component@4.x.
I had version 3.2.5 previously, with latest jest, and multiline comments were ok.

**Comment by ha404** [comment]
Having the same issue here and I don't have any multiline comments.

**Comment by yqbk** [comment]
For me the fix was to wrap component with `css`

```
export const subheaderStyle = `
  ${media.tablet`
      font-size: 16px;
  `};
`
const Subheader = styled(TextBase)`
  ${subheaderStyle};
`
```

should be:
```
export const subheaderStyle = css`
  ${media.tablet`
      font-size: 16px;
  `};
`
```

**Comment by abbyhowell** [comment]
For me, all I had to do was remove the `!` in `/*!` in the comments in my css reset.

**Comment by kitten** [comment]
@abbyhowell Glad to hear that it’s related to that! 🙌 I’ve opened a PR that should fix this particular issue https://github.com/styled-components/styled-components/pull/3018

**Comment by fredybustos** [comment]
I had this error and it also causes it, use the styles like this
Don't use these styles.

![Captura de Pantalla 2020-09-04 a la(s) 8 18 42 p  m](https://user-images.githubusercontent.com/9376106/92293829-29d8fb80-eeec-11ea-93d3-46d7421ecda5.png)

**Comment by probablyup** [comment]
Background is misspelled

**Comment by petros-zavrakas** [comment]
For me was more weird! Looks like ternary operator combined with template literals was the problem.

Following part wouldn't work 
```
${({ disabled, noBorder }) => 
  !disabled &&
    css`
      &:hover {
        border: ${noBorder ? '0' : `1px solid ${getStyles('borderColorHover')}`};
      }
    `}
```

I had to change it to this
```
${({ disabled, noBorder }) => 
  !disabled &&
    css`
      &:hover {
        ${!noBorder && css`border: 1px solid ${getStyles('borderColorHover')}`}
      }
    `}
```

The weird is that the following was working just fine
```
${({ centered }) => css`
  justify-content: ${centered ? 'center' : 'space-between'};
`}
```

**Comment by samwilliscreative** [comment]
I was getting this issue due to a google fonts import with multiple weights, which are separated by semi-colons. Separating the imports to multiple lines, with one weight per import resolves the issue, but I now have multiple http calls to get the fonts...
