### ISSUE TITLE
[Help Needed] Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by vizFlux** [styled-components/styled-components#2023]
Recently, I updated my project from 3.2.6 to 3.4.9 and I bump into an error, which I can't seem to find in which part of my code that causes it.

```Cannot convert a Symbol value to a string
TypeError: Cannot convert a Symbol value to a string
    at /Users/.../node_modules/styled-components/dist/styled-components.cjs.js:179:34
    at Array.map (<anonymous>)
    at objToCss (/Users/.../node_modules/styled-components/dist/styled-components.cjs.js:177:6)
    at /Users/.../node_modules/styled-components/dist/styled-components.cjs.js:178:41
    at Array.map (<anonymous>)
    at objToCss (/Users/.../node_modules/styled-components/dist/styled-components.cjs.js:177:6)
    at /Users/.../node_modules/styled-components/dist/styled-components.cjs.js:222:28
    at Array.reduce (<anonymous>)
    at flatten (/Users/.../node_modules/styled-components/dist/styled-components.cjs.js:185:17)
    at css (/Users/.../node_modules/styled-components/dist/styled-components.cjs.js:357:12)
    at /Users/.../node_modules/styled-components/dist/styled-components.cjs.js:207:25
    at Array.reduce (<anonymous>)
    at flatten (/Users/.../node_modules/styled-components/dist/styled-components.cjs.js:185:17)
    at /Users/.../node_modules/styled-components/dist/styled-components.cjs.js:213:37
    at Array.reduce (<anonymous>)
    at flatten (/Users/.../node_modules/styled-components/dist/styled-components.cjs.js:185:17)
```

I've looked through the issues, but those are caused by SVG as a component or nested components, and yet the errors show which file and line that causes them. They are somewhat different than what I'm encountering. So I wonder if anyone out there can help on this...

**Comment by probablyup** [comment]
Need a reproduction to be able to help at all

**Comment by vizFlux** [comment]
@probablyup That would be difficult because I have no idea where's the error coming from. Probably I need to look through again and see if I can narrow down the scope. Until then, I'll reopen if needed. Thanks!

**Comment by kumar303** [comment]
I landed on this from a search of the same error message. I had something like:

```js
const StyledContent = styled(Content);

const Container = styled.div`
  ${StyledContent} {
    width: 50%;
  }
`
```
I was getting the error because I forgot to add empty backticks 🤦 
```js
const StyledContent = styled(Content)``;

// ...
```
