### ISSUE TITLE
Chunk is not a constructor error when passing props

### ISSUE THREAD

**Issue by Pixelatex** [styled-components/styled-components#2207]
I'm using a storybook setup with CRA and everything works dandy, then I added styled components and things seemed to go haywire when you use props in a styled component.

note: This is only during the storybook snapshot tests that it crashes, everything else works as intended, removing the props from the component and everything runs smoothly, tests and all.

A component that crashes:
```
import React from 'react';
import PropTypes from 'prop-types';
import styled from 'styled-components'

const Card = ({ children, size }) => (
    <CardContainer size={size} >
        {children}
    </CardContainer>
)
const CardContainer = styled.div`
  border: 1px solid grey;
  border-radius: 5px;
  padding: 20px;
  width: ${props => props.size === 'fixed' ? '200px' : 'auto'}
`

Card.propTypes = {
    children: PropTypes.node
}

export default Card;
```

The error that occurs:
```
 console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8060
      The above error occurred in the <Context.Consumer> component:
          in StyledComponent (created by styled.input)
          in input (at input.stories.js:17)

      Consider adding an error boundary to your tree to customize error handling behavior.
      Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

  ● Storyshots › Input › default
    TypeError: chunk is not a constructor
      at flatten (node_modules/styled-components/dist/styled-components.cjs.js:1288:29)
      at flatten (node_modules/styled-components/dist/styled-components.cjs.js:1267:16)
      at ComponentStyle.generateAndInjectStyles (node_modules/styled-components/dist/styled-components.cjs.js:1474:19)
      at StyledComponent.generateAndInjectStyles (node_modules/styled-components/dist/styled-components.cjs.js:2136:36)
      at StyledComponent.renderInner (node_modules/styled-components/dist/styled-components.cjs.js:2043:33)
      at renderInner (node_modules/styled-components/dist/styled-components.cjs.js:1936:35)
      at updateContextConsumer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7275:19)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7441:14)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10138:12)
      at workLoop (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10170:24)
      at renderRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10256:7)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11121:7)      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11033:7)
      at performSyncWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11007:3)
      at requestWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10876:5)
      at scheduleWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10686:5)
      at scheduleRootUpdate (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11273:3)
      at updateContainerAtExpirationTime (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11301:10)
      at updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11312:10)
      at create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11828:5)
      at getRenderedTree (node_modules/@storybook/addon-storyshots/dist/frameworks/react/renderTree.js:20:16)
      at node_modules/@storybook/addon-storyshots/dist/test-bodies.js:21:18
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/api/snapshotsTestsTemplate.js:39:33)
```

**Comment by Fer0x** [comment]
@Pixelatex try upgrade to 4.1.1

**Comment by Pixelatex** [comment]
I am on 4.1.1 this is a fresh project, less than a day old.

**Comment by Fer0x** [comment]
@Pixelatex are you sure? I can reproduce it with https://codesandbox.io/s/04n191v3wv
Also, 4.1.1 was cut 15 hours ago exactly with this bug fix
