### ISSUE TITLE
Could not parse CSS stylesheet when running a test

### ISSUE THREAD

**Issue by DavidHe1127** [styled-components/styled-components#2393]
## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 5.13 GB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 8.11.4 - ~/.nvm/versions/node/v8.11.4/bin/node
 - Yarn: 1.13.0 - ~/.nvm/versions/node/v8.11.4/bin/yarn
 - npm: 6.7.0 - ~/.nvm/versions/node/v8.11.4/bin/npm
## npmPackages:
 - styled-components: ^4.1.3 => 4.1.3
- jest 23.6.0

## Steps to reproduce
Run test below in CRA.
```
import React from 'react';
import ReactDOM from 'react-dom';

import styled from 'styled-components';

const Base = styled.div`
  @-ms-viewport {
    width: device-width;
  }

  div {
    height: 12px;
  }
`;

it('renders without crashing', () => {
  const div = document.createElement('div');
  ReactDOM.render(
    <div>
      <Base />
    </div>,
    div
  );
  ReactDOM.unmountComponentAtNode(div);
});
```

## Expected Behavior
Test passed with no errors
## Actual Behavior
Test passed with error as follow

```
  console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Could not parse CSS stylesheet
        at exports.createStylesheet (/Users/P782199/index-component-test/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:35:21)
        at HTMLStyleElementImpl._updateAStyleBlock (/Users/P782199/index-component-test/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:67:5)
        at HTMLStyleElementImpl._childTextContentChangeSteps (/Users/P782199/index-component-test/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:36:12)
        at TextImpl.replaceData (/Users/P782199/index-component-test/node_modules/jsdom/lib/jsdom/living/nodes/CharacterData-impl.js:73:23)
        at TextImpl.appendData (/Users/P782199/index-component-test/node_modules/jsdom/lib/jsdom/living/nodes/CharacterData-impl.js:43:10)
        at Text.appendData (/Users/P782199/index-component-test/node_modules/jsdom/lib/jsdom/living/generated/CharacterData.js:76:21)
        at Object.insertRules (/Users/P782199/index-component-test/node_modules/styled-components/dist/styled-components.cjs.js:674:16)
        at StyleSheet.inject (/Users/P782199/index-component-test/node_modules/styled-components/dist/styled-components.cjs.js:1101:11)
        at ComponentStyle.generateAndInjectStyles (/Users/P782199/index-component-test/node_modules/styled-components/dist/styled-components.cjs.js:1487:18)
        at StyledComponent.generateAndInjectStyles (/Users/P782199/index-component-test/node_modules/styled-components/dist/styled-components.cjs.js:2148:29)
    /* sc-component-id: sc-bdVaJa */
    @-ms-viewport{.iNSDVR{width:device-width;}}

  console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Could not parse CSS stylesheet
        at exports.createStylesheet (/Users/P782199/index-component-test/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:35:21)
        at HTMLStyleElementImpl._updateAStyleBlock (/Users/P782199/index-component-test/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:67:5)
        at HTMLStyleElementImpl._childTextContentChangeSteps (/Users/P782199/index-component-test/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:36:12)
        at TextImpl.replaceData (/Users/P782199/index-component-test/node_modules/jsdom/lib/jsdom/living/nodes/CharacterData-impl.js:73:23)
        at TextImpl.appendData (/Users/P782199/index-component-test/node_modules/jsdom/lib/jsdom/living/nodes/CharacterData-impl.js:43:10)
        at Text.appendData (/Users/P782199/index-component-test/node_modules/jsdom/lib/jsdom/living/generated/CharacterData.js:76:21)
        at Object.insertRules (/Users/P782199/index-component-test/node_modules/styled-components/dist/styled-components.cjs.js:674:16)
        at StyleSheet.inject (/Users/P782199/index-component-test/node_modules/styled-components/dist/styled-components.cjs.js:1101:11)
        at ComponentStyle.generateAndInjectStyles (/Users/P782199/index-component-test/node_modules/styled-components/dist/styled-components.cjs.js:1487:18)
        at StyledComponent.generateAndInjectStyles (/Users/P782199/index-component-test/node_modules/styled-components/dist/styled-components.cjs.js:2148:29)
    /* sc-component-id: sc-bdVaJa */
    @-ms-viewport{.iNSDVR{width:device-width;}} .iNSDVR div{height:12px;}
```

## potentially relate to 
https://github.com/styled-components/styled-components/issues/1931
https://github.com/styled-components/styled-components/issues/1690

**Comment by tomspeak** [comment]
I am also facing this issue. Did you manage to resolve it? None of the fixes in the other thread work for me.

**Comment by tomspeak** [comment]
Luckily I fixed this, it turned out to be a tiny syntax error that was hard to spot.

```diff
- height: '100%;
+ height: '100%';
```

**Comment by yqbk** [comment]
For me fixed by wrapping code with `css` 
https://github.com/styled-components/styled-components/issues/1931#issuecomment-568180246

**Comment by akursat** [comment]
I got this error because I added "GlobalStyles" to the custom render. The warnings are gone when I delete it.
