### ISSUE TITLE
`Define a theme interface` documentation doesn't work with macro import

### ISSUE THREAD

**Issue by codepunkt** [styled-components/styled-components#2423]
#### System
 - OS: Windows 10 - CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
 - Memory: 940.17 MB / 15.64 GB
#### Binaries:
 - Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.13.0 - ~\AppData\Roaming\npm\yarn.CMD
 - npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD

## Steps to reproduce
- Create `theme.ts` and `styled-components.ts` as described [in the documentation section "Define a theme interface"](https://www.styled-components.com/docs/api#define-a-theme-interface).
- Change the styled-components import in `styled-components.ts` from `styled-components` to `styled-components/macro`

## Expected Behavior
- Developer friendly classnames in development via /macro
- typed `props.theme`

## Actual Behavior
```
./src/style/styled-components.ts
TypeError: Cannot read property 'name' of undefined at Array.map (<anonymous>)
```

**Comment by chriserickson** [comment]
I'm seeing this as well. If it is helpful, here is more of a stack trace that I've been able to get:

```
at /node_modules/babel-plugin-macros/dist/index.js:134:19
    at Array.map (<anonymous>)
    at PluginPass.ImportDeclaration (/node_modules/babel-plugin-macros/dist/index.js:133:44)
    at newFn (/node_modules/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/node_modules/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/node_modules/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/node_modules/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/node_modules/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/node_modules/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/node_modules/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/node_modules/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/node_modules/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/node_modules/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/node_modules/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/node_modules/@babel/traverse/lib/index.js:94:17)
```
The line that is causing the issue is /Users/chris/src/om/ui/direct/node_modules/babel-plugin-macros/dist/index.js#89:
```
          var imports = path.node.specifiers.map(function(s) {
          return {
            localName: s.local.name,
            importedName:
              s.type === 'ImportDefaultSpecifier' ? 'default' : s.imported.name,
          };
        });
```

And the value of `s` is:
```
Node {
  type: 'ImportNamespaceSpecifier',
  start: 7,
  end: 28,
  loc:
   SourceLocation {
     start: Position { line: 1, column: 7 },
     end: Position { line: 1, column: 28 } },
  local:
   Node {
     type: 'Identifier',
     start: 12,
     end: 28,
     loc:
      SourceLocation {
        start: [Position],
        end: [Position],
        identifierName: 'styledComponents' },
     name: 'styledComponents' 
   } 
}
```

**Comment by chriserickson** [comment]
The workaround described here makes things work:
https://github.com/styled-components/styled-components/issues/2368#issuecomment-462507866

**Comment by Ciberusps** [comment]
@chriserickson ty works for me also
