### ISSUE TITLE
v5 canary: module build failed for sandbox

### ISSUE THREAD

**Issue by haldunanil** [styled-components/styled-components#2613]
### System:
 - OS: macOS High Sierra 10.13.6
 - CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
 - Memory: 469.31 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
### Binaries:
 - Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
 - Yarn: 1.16.0 - /usr/local/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman

## Steps to reproduce

* Fork the styled-components repo
* Checkout `canary` branch
* `cd` into `packages/sandbox`
* Do `yarn` to install dependencies
* Do `yarn start`

> Note: deleting `node_modules` and running `yarn cache clean` also did not fix the problem.

## Expected Behavior

Sandbox page loads and functions as expected.

## Actual Behavior

Getting this error:

```
Error: Module build failed (from /Users/halani/Desktop/styled-components/node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/halani/Desktop/styled-components/node_modules/babel-preset-react/lib/index.js
    at createDescriptor (/Users/halani/Desktop/styled-components/node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
    at items.map (/Users/halani/Desktop/styled-components/node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (/Users/halani/Desktop/styled-components/node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
    at createPresetDescriptors (/Users/halani/Desktop/styled-components/node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
    at presets (/Users/halani/Desktop/styled-components/node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
    at mergeChainOpts (/Users/halani/Desktop/styled-components/node_modules/@babel/core/lib/config/config-chain.js:320:26)
    at /Users/halani/Desktop/styled-components/node_modules/@babel/core/lib/config/config-chain.js:283:7
    at buildRootChain (/Users/halani/Desktop/styled-components/node_modules/@babel/core/lib/config/config-chain.js:120:22)
    at loadPrivatePartialConfig (/Users/halani/Desktop/styled-components/node_modules/@babel/core/lib/config/partial.js:85:55)
    at createError (/Users/halani/Desktop/styled-components/node_modules/micro/lib/index.js:20:14)
    at module.exports (/Users/halani/Desktop/styled-components/packages/sandbox/server/index.js:11:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by probablyup** [comment]
Sorry about that, should be fixed if you pull latest from canary :)
