### ISSUE TITLE
Missing initializer in const declaration (using Next.js with react-native-web)

### ISSUE THREAD

**Issue by Lpaydat** [styled-components/styled-components#2843]
### System:
 - OS: macOS Mojave 10.14.4
 - CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
 - Memory: 117.38 MB / 8.00 GB
 - Shell: 4.4.23 - /usr/local/bin/bash
### Binaries:
 - Node: 10.16.0 - /usr/local/bin/node
 - Yarn: 1.19.1 - ~/.yarn/bin/yarn
 - npm: 6.11.3 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
### npmPackages:
 - babel-plugin-styled-components: ^1.10.6 => 1.10.6
 - styled-components: ^4.4.1 => 4.4.1
 - react-native-web: ^0.11.7

## Expected Behavior
Can use `styled-components` together with `next.js` and `react-native-web`

## Actual Behavior
Code works well without `styled-components` (I use `import styled from 'styled-components/native` to create styled components).

Got the error: (the same issue also occurs on 5.0.0 latest beta version)
```
Missing initializer in const declaration

/Users/me/workspace/project_name/node_modules/react-native/Libraries/Utilities/warnOnce.js:15
const warnedKeys: {[string]: boolean} = {};
      ^^^^^^^^^^

SyntaxError: Missing initializer in const declaration
    at Module._compile (internal/modules/cjs/loader.js:721:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/me/workspace/project_name/node_modules/react-native/Libraries/react-native/react-native-implementation.js:14:18)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/me/workspace/project_name/node_modules/styled-components/native/dist/styled-components.native.cjs.js:6498:19)
```

**Comment by Lpaydat** [comment]
Fixed.

It turns out to be the issue of TypeScript issue. (fix by following this method [StackOverflow](https://stackoverflow.com/questions/57815082/nextjs-react-native-web-styled-components-warnonce))

**Comment by SunskyXH** [comment]
Hi, sorry to bother you, I've met the same problem, and I tried the fix in your link, but here comes another problem. Do I miss any detail?

> [ error ] ../node_modules/react-native/Libraries/react-native/react-native-implementation.js
Module not found: Can't resolve '../Components/AccessibilityInfo/AccessibilityInfo' in '/node_modules/react-native/Libraries/react-native'
