### ISSUE TITLE
Suddent error on all project thats use styled-components

### ISSUE THREAD

**Issue by kopax** [styled-components/styled-components#2905]
Hello, we have an issue on all our pipelines that use styled-components:

```
Error: Package exports for '/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/merge-anything' do not define a '.' subpath
Error: Package exports for '/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/merge-anything' do not define a '.' subpath
    at resolveExports (internal/modules/cjs/loader.js:419:17)
    at Function.Module._findPath (internal/modules/cjs/loader.js:492:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:787:27)
    at Function.Module._load (internal/modules/cjs/loader.js:693:27)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/dka/workspace/github.com/bootstrap-styled/provider/node_modules/styled-components/dist/styled-components.cjs.js:17:29)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)

```

No idea what that is we're still investigating.

**Comment by kopax** [comment]
it was core-js
