### ISSUE TITLE
No valid exports main found for `merge-anything`

### ISSUE THREAD

**Issue by bmamouri** [styled-components/styled-components#2907]
### System:
 - OS: macOS 10.15.1
 - CPU: (4) x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
 - Memory: 5.57 GB / 24.00 GB
 - Shell: 5.7.1 - /bin/zsh
### Binaries:
 - Node: 13.2.0 - /usr/local/opt/node/bin/node
 - Yarn: 1.19.2 - /usr/local/bin/yarn
 - npm: 6.11.3 - /usr/local/opt/node@10/bin/npm

## Reproduction
An [issue](https://github.com/styled-components/styled-components/issues/115) from back 2016 has been re-surfaced with Node 13. The issue is caused by `merge-anything` dependency with the following error:

```
Error: No valid exports main found for 'REDACTED/node_modules/merge-anything'
    at resolveExportsTarget (internal/modules/cjs/loader.js:611:9)
    at applyExports (internal/modules/cjs/loader.js:492:14)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:643:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:941:27)
    at Function.Module._load (internal/modules/cjs/loader.js:847:27)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.<anonymous> (REDACTED/node_modules/styled-components/dist/styled-components.cjs.js:17:29)
    at Module._compile (internal/modules/cjs/loader.js:1121:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1160:10)
    at Module.load (internal/modules/cjs/loader.js:976:32)
    at Function.Module._load (internal/modules/cjs/loader.js:884:14)
    at Module.require (internal/modules/cjs/loader.js:1016:19)
    at require (internal/modules/cjs/helpers.js:69:18)
    at Object.styled-components (REDACTED/packages/REDACTEd/dist/server/static/development/pages/_document.js:1820:18) {
  code: 'MODULE_NOT_FOUND'
```

## Steps to reproduce
Unfortunately, I can't seem to reproduce the issue without using Next.js. So it is possible that the issue is caused by their Babel or Webpack configuration. But I thought to post here to see if someone have a workaround. 

Feel free to close if it is against the rules.

[The related issue in Next.js](https://github.com/zeit/next.js/issues/9582)

**Comment by probablyup** [comment]
Try blowing away your node modules, it’s definitely fine.

**Comment by bmamouri** [comment]
I've tried that several times @probablyup. Unfortunately, I still get the same error!

**Comment by probablyup** [comment]
It must be something to do with your build system then... it definitely
works fine. Make sure you’re on an updated version etc

**Comment by maiopirata** [comment]
@bmamouri look here https://github.com/mesqueeb/merge-anything/issues/2
Actually the  more simple thing you can do is to upgrade styled-components to the next version
```yarn add styled-component@beta```

**Comment by probablyup** [comment]
Closing since it's a downstream issue
