### ISSUE TITLE
RangeError: Invalid typed array length: -2147483648

### ISSUE THREAD

**Issue by boyuan459** [styled-components/styled-components#3027]
## Environment
Next.js + React 16.8

## Reproduction

Cannot be reproduced, server run out of memory and crash and then restart

## Actual Behavior
Server keeps restarting
RangeError: Invalid typed array length: -2147483648
    at new Uint32Array (<anonymous>)
    at DefaultGroupedTag.insertRules (/app/node_modules/styled-components/dist/styled-components.cjs.js:335:25)
    at StyleSheet.insertRules (/app/node_modules/styled-components/dist/styled-components.cjs.js:579:19)
    at ComponentStyle.generateAndInjectStyles (/app/node_modules/styled-components/dist/styled-components.cjs.js:1290:20)
    at useInjectedStyle (/app/node_modules/styled-components/dist/styled-components.cjs.js:1463:120)
    at useStyledComponentImpl (/app/node_modules/styled-components/dist/styled-components.cjs.js:1490:28)
    at Object.forwardRef [as render] (/app/node_modules/styled-components/dist/styled-components.cjs.js:1543:12)
    at a.render (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:43:60)
    at a.read (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:58)
    at renderToString (/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:53:83)

**Comment by probablyup** [comment]
Are you using 5.0.1?

**Comment by boyuan459** [comment]
We used to use 5.0.1, encounter this problem, and then downgrade to 4.x, still has this problem

**Comment by kitten** [comment]
In 5.0.1 we fixed this issue and in v4 the affected code that uses UInt32array doesn’t exist, so can you double check the versions please?

**Comment by boyuan459** [comment]
we just solved this problem by removing two other createGlobalStyle and only keep one createGlobalStyle in our project, all styled-components errors are gone, so my assumption is we can only use one createGlobalStyle in our next.js project.
