### ISSUE TITLE
Bug: Crash in React Native when prop name is "start"

### ISSUE THREAD

**Issue by arnaudambro** [styled-components/styled-components#3190]
### System:
 - OS: macOS 10.15.5
 - CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
 - Memory: 189.56 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
### Binaries:
 - Node: 10.16.0 - /usr/local/bin/node
 - Yarn: 1.22.4 - /usr/local/bin/yarn
 - npm: 6.9.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
### npmPackages:
 - styled-components: ^5.0.0 => 5.0.1

Use in React Native 0.61.5

## Reproduction
```jsx
import React from 'react';
import styled from 'styled-components';
import { Text, TouchableWithoutFeedback } from 'react-native';

export default ({ onPress }) => (
  <ButtonsContainer start>
    <TouchableWithoutFeedback
      onPress={onPress}
      hitSlop={{ top: 40, bottom: 40, left: 40, right: 40 }}>
      <Text>Press me</Text>
    </TouchableWithoutFeedback>
  </ButtonsContainer>
)

const ButtonsContainer = styled.View`
  flex-direction: row;
  justify-content: ${props => (props.start ? 'flex-start' : 'space-around')};
  align-items: center;
  width: 100%;
`;
```

## Expected Behavior
No crash

## Actual Behavior
Crash on Android :
```err
Error while updating prop start
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateShadowNodeProp(ViewManagersPropertyCache.java:112)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackShadowNodeSetter.setProperty(ViewManagerPropertyUpdater.java:159)
	at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:63)
	at com.facebook.react.uimanager.ReactShadowNodeImpl.updateProperties(ReactShadowNodeImpl.java:318)
	at com.facebook.react.uimanager.UIImplementation.createView(UIImplementation.java:249)
	at com.facebook.react.uimanager.UIManagerModule.createView(UIManagerModule.java:465)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
	at android.os.Looper.loop(Looper.java:214)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.Double
	at com.facebook.react.bridge.DynamicFromObject.asDouble(DynamicFromObject.java:38)
	at com.facebook.react.uimanager.LayoutShadowNode$MutableYogaValue.setFromDynamic(LayoutShadowNode.java:65)
	at com.facebook.react.uimanager.LayoutShadowNode.setPositionValues(LayoutShadowNode.java:739)
	... 17 more
```

#### Don't call a prop `start` when using `styled-components`

**Comment by kitten** [comment]
This isn't a bug per se; The `start` prop there seems to actually be picked up by React Native on the builtin component you're rendering. Since props aren't filtered in styled-components for React Native you must make sure that your props never overlap with props that the component accepts.
