### ISSUE TITLE
Why does the task Webpack DLL complain when trying to import another module.

### ISSUE THREAD

**Issue by kopax** [styled-components/styled-components#332]
Following #326, I did like advised and restarted a whole project using the configuration of the react boilerplate and the links provided.

```ruby
Building the Webpack DLL...
/workspace/git.domain.com/domain/backoffice/node_modules/babel-core/lib/transformation/file/options/option-manager.js:334
        throw e;
        ^

Error: Options {"es2015":{"modules":false}} passed to /workspace/git.domain.com/domain/backoffice/node_modules/babel-preset-latest/lib/index.js which does not accept options. (While processing preset: "/workspace/git.domain.com/domain/backoffice/node_modules/babel-preset-latest/lib/index.js") (While processing preset: "/workspace/git.domain.com/domain/backoffice/node_modules/babel-preset-latest/lib/index.js")
    at /workspace/git.domain.com/domain/backoffice/node_modules/babel-core/lib/transformation/file/options/option-manager.js:320:17
    at Array.map (native)
    at OptionManager.resolvePresets (/workspace/git.domain.com/domain/backoffice/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/workspace/git.domain.com/domain/backoffice/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/workspace/git.domain.com/domain/backoffice/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/workspace/git.domain.com/domain/backoffice/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at compile (/workspace/git.domain.com/domain/backoffice/node_modules/babel-register/lib/node.js:103:45)
    at loader (/workspace/git.domain.com/domain/backoffice/node_modules/babel-register/lib/node.js:144:14)
    at Object.require.extensions.(anonymous function) [as .js] (/workspace/git.domain.com/domain/backoffice/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
- react-boilerplate-dlls@0.1.0 node_modules/bootstrap-styled/node_modules/react-boilerplate-dlls
react-boilerplate@3.3.3 /workspace/git.domain.com/domain/backoffice
├── bootstrap-styled@0.1.0  (git+ssh://git@github.com/domain/bootstrap-styled.git#56be7063e024cfce5a6b973bddc1956cf4f5133a)
├── UNMET PEER DEPENDENCY eslint-plugin-import@2.0.1
└── UNMET PEER DEPENDENCY react@15.3.2

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN eslint-config-airbnb@12.0.0 requires a peer of eslint-plugin-import@^1.16.0 but none was installed.
npm WARN eslint-config-airbnb-base@8.0.0 requires a peer of eslint-plugin-import@^1.16.0 but none was installed.
npm WARN react-dom@15.4.1 requires a peer of react@^15.4.1 but none was installed.
npm WARN scroll-behavior@0.8.2 requires a peer of history@^1.12.1 || ^2.0.0 but none was installed.
dka@dev-01:[/workspace/git.domain.com/domain/backoffice]: 

```

This error happen when I try to do a `npm install git+https://git@github.com:kopaxgroup/bootstrap-styled.git --save`

I have defined my module as follow :  

```jsx
  output: {
    // filename: '[name].[chunkhash].js',
    filename: 'bootstrap-styled.js',
    library: "bootstrap-styled", // string,
    libraryTarget: "commonjs-module", // enum
  },
```

What is the purpose of this dll and why does he refuse my module ?

**Comment by k15a** [comment]
Because you're building a library and not an application you most likely don't need the full blown react-boilerblate webpack config. Try to look at some webpack configs of libraries. For example redux or react-redux. You could also look at these projects: https://github.com/styled-components/styled-components#built-with-styled-components. In addition I would advise you to read the [webpack@2 docs](https://webpack.js.org/) or at least the [concepts](https://webpack.js.org/concepts/) so you can understand what webpack does. In your current situation I think it would be enough if you transpile the files with babel (`babel input-dir -o output-dir`) unless you want a separate UMD bundle.
