### ISSUE TITLE
ReferenceError: window is not defined - NextJs 10.1.2 w/ Webpack5 enabled

### ISSUE THREAD

**Issue by wadehammes** [styled-components/styled-components#3444]
### System:
 - OS: Linux 4.19 Ubuntu 18.04.5 LTS (Bionic Beaver)
 - CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
 - Memory: 21.27 GB / 25.01 GB
 - Container: Yes
 - Shell: 5.4.2 - /usr/bin/zsh
### Binaries:
 - Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
 - Yarn: 1.22.5 - /usr/bin/yarn
 - npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
### npmPackages:
 - babel-plugin-styled-components: ^1.12.0 => 1.12.0 
 - styled-components: ^5.2.2 => 5.2.2

## Steps to reproduce
1. Using NextJS 10.1.2 with the future flag for Webpack 5 enabled
2. Running `npm dev` or `npm build` results in the below error:

```
ReferenceError: window is not defined
    at k (/home/wade/Code/Clients/rhythm-marketing/node_modules/styled-components/dist/styled-components.cjs.js:1:7161)
    at e.getStyleElement (/home/wade/Code/Clients/rhythm-marketing/node_modules/styled-components/dist/styled-components.cjs.js:1:22622)
    at Function.getInitialProps (/home/wade/Code/Clients/rhythm-marketing/.next/server/pages/_document.js:1148:49)
    at async loadGetInitialProps (/home/wade/Code/Clients/rhythm-marketing/node_modules/next/dist/next-server/lib/utils.js:5:91)
    at async renderToHTML (/home/wade/Code/Clients/rhythm-marketing/node_modules/next/dist/next-server/server/render.js:54:1110)
    at async /home/wade/Code/Clients/rhythm-marketing/node_modules/next/dist/next-server/server/next-server.js:112:97
    at async /home/wade/Code/Clients/rhythm-marketing/node_modules/next/dist/next-server/server/next-server.js:105:142
    at async DevServer.renderToHTMLWithComponents (/home/wade/Code/Clients/rhythm-marketing/node_modules/next/dist/next-server/server/next-server.js:137:387)
    at async DevServer.renderErrorToHTML (/home/wade/Code/Clients/rhythm-marketing/node_modules/next/dist/next-server/server/next-server.js:139:505)
    at async DevServer.renderErrorToHTML (/home/wade/Code/Clients/rhythm-marketing/node_modules/next/dist/server/next-dev-server.js:35:1380)
    at async DevServer.renderToHTML (/home/wade/Code/Clients/rhythm-marketing/node_modules/next/dist/next-server/server/next-server.js:138:1281)
    at async DevServer.renderToHTML (/home/wade/Code/Clients/rhythm-marketing/node_modules/next/dist/server/next-dev-server.js:35:578)
    at async DevServer.render (/home/wade/Code/Clients/rhythm-marketing/node_modules/next/dist/next-server/server/next-server.js:75:236)
    at async Object.fn (/home/wade/Code/Clients/rhythm-marketing/node_modules/next/dist/next-server/server/next-server.js:59:580)
    at async Router.execute (/home/wade/Code/Clients/rhythm-marketing/node_modules/next/dist/next-server/server/router.js:25:67)
    at async DevServer.run (/home/wade/Code/Clients/rhythm-marketing/node_modules/next/dist/next-server/server/next-server.js:69:1042)
ReferenceError: window is not defined
    at k (/home/wade/Code/Clients/rhythm-marketing/node_modules/styled-components/dist/styled-components.cjs.js:1:7161)
    at e.getStyleElement (/home/wade/Code/Clients/rhythm-marketing/node_modules/styled-components/dist/styled-components.cjs.js:1:22622)
    at Function.getInitialProps (/home/wade/Code/Clients/rhythm-marketing/.next/server/pages/_document.js:1148:49)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async loadGetInitialProps (/home/wade/Code/Clients/rhythm-marketing/node_modules/next/dist/next-server/lib/utils.js:5:91)
    at async renderToHTML (/home/wade/Code/Clients/rhythm-marketing/node_modules/next/dist/next-server/server/render.js:54:1110)
    at async /home/wade/Code/Clients/rhythm-marketing/node_modules/next/dist/next-server/server/next-server.js:112:97
    at async __wrapper (/home/wade/Code/Clients/rhythm-marketing/node_modules/next/dist/lib/coalesced-function.js:1:330)
    at async DevServer.renderToHTMLWithComponents (/home/wade/Code/Clients/rhythm-marketing/node_modules/next/dist/next-server/server/next-server.js:137:387)
    at async DevServer.renderToHTML (/home/wade/Code/Clients/rhythm-marketing/node_modules/next/dist/next-server/server/next-server.js:138:522)
    at async DevServer.renderToHTML (/home/wade/Code/Clients/rhythm-marketing/node_modules/next/dist/server/next-dev-server.js:35:578)
    at async DevServer.render (/home/wade/Code/Clients/rhythm-marketing/node_modules/next/dist/next-server/server/next-server.js:75:236)
    at async Object.fn (/home/wade/Code/Clients/rhythm-marketing/node_modules/next/dist/next-server/server/next-server.js:59:580)
    at async Router.execute (/home/wade/Code/Clients/rhythm-marketing/node_modules/next/dist/next-server/server/router.js:25:67)
    at async DevServer.run (/home/wade/Code/Clients/rhythm-marketing/node_modules/next/dist/next-server/server/next-server.js:69:1042)
```

## Expected Behavior
This error does not occur with `styled-components: ^5.1.2`

## Actual Behavior
The above error occurs and I am unable to build my project.

**Comment by wadehammes** [comment]
> Same issue here, same configuration, without the Webpack 5 flag enabled.

I also am unable to build with the webpack5 flag removed using `5.1.2`

**Comment by sanpol333** [comment]
see this commit
https://github.com/styled-components/styled-components/commit/15b07960718a4fcd0d15ff407a4dee271e8a0c3e

window.__webpack_nonce__?

**Comment by rafifos** [comment]
The error **does** occur when using `styled-components: ^5.2.1` (which is atm being resolved to 5.2.2 in when using yarn without a lockfile)

**Comment by tony99nyr** [comment]
Server side rendering in general is busted on 5.2.2. We have rolled back to 5.2.1 and the issue is resolved. 

If it helps, this was the stack trace:
```
ERROR Master [Anonymous] ReferenceError: window is not defined
    at id (/mnt/g/app/node_modules/styled-components/src/constants.js:4:33)
    at e.id [as _emitSheetCSS] (/mnt/g/app/node_modules/styled-components/src/models/GlobalStyle.js:28:11)
    at e.getStyleTags (/mnt/g/app/node_modules/styled-components/src/models/GlobalStyle.js:28:11)

**Comment by Rouncer27** [comment]
This was also happening on Gatsby build on Netlify, fixed by rolling back to version 5.2.1

This was the stack trace, hope this helps!
 
`failed Building static HTML for pages - 9.641s`
`error "window" is not available during server side rendering.`
`> 1 | import{typeOf as e,isElement as t,isValidElementType as n}from"react-is";import r,{useState as `

**Comment by giobassetto** [comment]
For me don't works the solution i used the version 5.2.0 in my project. I try upgrade to version 5.2.1 but not works.
This is the stacktrace:
```
#12 101.8 Error occurred prerendering page "/terms". Read more: https://err.sh/next.js/prerender-error
#12 101.8 ReferenceError: window is not defined
#12 101.8     at k (/build/node_modules/styled-components/dist/styled-components.cjs.js:1:7161)
#12 101.8     at e.getStyleElement (/build/node_modules/styled-components/dist/styled-components.cjs.js:1:22622)
#12 101.8     at Function.getInitialProps (/build/.next/server/pages/_document.js:824:111)
#12 101.8     at async loadGetInitialProps (/build/node_modules/next/dist/next-server/lib/utils.js:5:91)
#12 101.8     at async renderToHTML (/build/node_modules/next/dist/next-server/server/render.js:50:1107)
#12 101.8     at async Object.exportPage [as default] (/build/node_modules/next/dist/export/worker.js:25:6)
```

**Comment by ujwal-setlur** [comment]
v5.2.1 with next 10.1.2 works for me. Why did a minor release break things?

**Comment by edoko** [comment]
Same here v5.2.2 with Next.js v10.1.2 via webpack 4.

I returned v5.2.1 and it works successfully.

**Comment by cksiazak** [comment]
With Next.js v10.1.2 and using both webpack 4 and 5, I needed to return to styled-components v5.2.0 for it to work properly

**Comment by mikevercoelen** [comment]
Bump

**Comment by inside** [comment]
Hi, I'm using [this nextjs styled-components example](https://github.com/vercel/next.js/blob/canary/examples/with-styled-components/README.md).
I also confirm the bug with `styled-components@5.2.2` and installing `styled-components@5.2.1` doesn't have the bug.

**Comment by sl-julienamblard** [comment]
Hello, same error with Next 9+ and ssr pages. Fixing dependecy to 5.2.1 solve the problem, looking forward for a 5.2.3 ^^

**Comment by NishargShah** [comment]
Styled Components just released the version `V5.2.2` and it includes the `window` that's why it's giving this error.

https://github.com/styled-components/styled-components/compare/v5.2.1...v5.2.2#diff-0d2f0aea19de7446797f235f62c09253e4ee01d14d9f5efa736835bc82c302c0R400

**Comment by pierot** [comment]
redoc-cli failing with the same error:

```
ReferenceError: window is not defined
    at k (xxx/node_modules/redoc-cli/node_modules/styled-components/dist/styled-components.cjs.js:1:7161)
    at e._emitSheetCSS (xxx/node_modules/redoc-cli/node_modules/styled-components/dist/styled-components.cjs.js:1:22249)
    at e.getStyleTags (xxx/node_modules/redoc-cli/node_modules/styled-components/dist/styled-components.cjs.js:1:22428)
    at xxx/node_modules/redoc-cli/index.js:216:25
    at Generator.next (<anonymous>)
    at fulfilled (xxx/node_modules/redoc-cli/index.js:6:58)
```

**Comment by hpachy** [comment]
Hi @pierot  ,you can try to downgrade to v5.2.1 it's work for most of us

**Comment by pierot** [comment]
I can't see how I should do this, as `styled-components` is a dependency of `redoc-cli`. I raised an [issue](https://github.com/Redocly/redoc/issues/1563) over there as well.

**Comment by eric-burel** [comment]
> I can't see how I should do this, as `styled-components` is a dependency of `redoc-cli`. I raised an [issue](https://github.com/Redocly/redoc/issues/1563) over there as well.
You can force versions using [Yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) for instance. That forces the version for subdependencies as well.

**Comment by FabricioPaschoal** [comment]
I had the same problem when generating the build in NextJS in version 10.0.7 with styled-components in version "^ 5.2.1". The solution was to remove stylized components and reinstalled, fixing it in version 5.2.0.

`` `
yarn remove styled-components
yarn add styled-components@5.2.0
```

**Comment by probablyup** [comment]
Fix is out in 5.2.3

**Comment by rwieruch** [comment]
Would this still be a problem if one is using only 

```
babel-plugin-styled-components: ^1.12.0
```

in a project?
