### ISSUE TITLE
Enzyme doesn't mount styled-components

### ISSUE THREAD

**Issue by alinanovof** [styled-components/styled-components#3629]
## System:
 - OS: Windows 10 10.0.19042
 - CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
 - Memory: 4.34 GB / 15.76 GB
## Binaries:
 - Node: 16.5.0 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 7.19.1 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - styled-components: ^5.3.3 => 5.3.3

## Reproduction

I have a Jest/Enzyme test for 2 styled components that don't work when I try to mount them. Both of the components are pretty simple and they don't work even if I try mounting it after deleting everything on the inside and outside, so only dummy styled component is left.
Both of the components are the last children of a few nested components.
At the same time, Enzyme's 'shallow' works wit both of these components.

## Expected Behavior
Mounting components in Enzyme and testing them successfully

## Actual Behavior
```
 TypeError: Cannot read property 'length' of undefined
        at $ (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\styled-components\src\utils\isStaticRules.js:6:39)
        at e.useDebugValue [as generateAndInjectStyles] (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\styled-components\src\models\ComponentStyle.js:89:40)
        at $as (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\styled-components\src\models\StyledComponent.js:90:46)
        at displayName (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\styled-components\src\models\StyledComponent.js:134:57)
        at I (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\styled-components\src\models\StyledComponent.js:252:26)
        at renderWithHooks (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\react-dom\cjs\react-dom.development.js:14803:18)
        at updateForwardRef (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\react-dom\cjs\react-dom.development.js:16816:20)
        at beginWork (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\react-dom\cjs\react-dom.development.js:18645:16)
        at HTMLUnknownElement.callCallback (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\react-dom\cjs\react-dom.development.js:188:14)
        at invokeEventListeners (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:193:27)
        at HTMLUnknownElementImpl._dispatch (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\nodes\HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\react-dom\cjs\react-dom.development.js:237:16)
        at invokeGuardedCallback (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\react-dom\cjs\react-dom.development.js:292:31)
        at beginWork$1 (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\react-dom\cjs\react-dom.development.js:23203:7)
        at performUnitOfWork (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\react-dom\cjs\react-dom.development.js:22157:12)
        at workLoopSync (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\react-dom\cjs\react-dom.development.js:22130:22)
        at performSyncWorkOnRoot (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\react-dom\cjs\react-dom.development.js:21756:9)
        at scheduleUpdateOnFiber (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\react-dom\cjs\react-dom.development.js:21188:7)
        at updateContainer (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\react-dom\cjs\react-dom.development.js:24373:3)
        at C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\react-dom\cjs\react-dom.development.js:24758:7
        at unbatchedUpdates (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\react-dom\cjs\react-dom.development.js:21903:12)
        at legacyRenderSubtreeIntoContainer (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\react-dom\cjs\react-dom.development.js:24757:5)
        at Object.render (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\react-dom\cjs\react-dom.development.js:24840:10)
        at fn (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\enzyme-adapter-react-16\src\ReactSixteenAdapter.js:488:26)
        at C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\enzyme-adapter-react-16\src\ReactSixteenAdapter.js:405:37
        at batchedUpdates$1 (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\react-dom\cjs\react-dom.development.js:21856:12)
        at Object.act (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\react-dom\cjs\react-dom-test-utils.development.js:929:14)
        at wrapAct (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\enzyme-adapter-react-16\src\ReactSixteenAdapter.js:405:13)
        at Object.render (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\enzyme-adapter-react-16\src\ReactSixteenAdapter.js:474:16)
        at new ReactWrapper (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\enzyme\src\ReactWrapper.js:115:16)
        at mount (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\enzyme\src\mount.js:10:10)
        at Object.<anonymous> (C:\Users\alya0\Documents\Enroute\enroute-web\src\__tests__\ProductBanner.test.js:86:4)
        at Object.asyncJestTest (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
        at new Promise (<anonymous>)
        at mapper (C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
        at C:\Users\alya0\Documents\Enroute\enroute-web\node_modules\jest-jasmine2\build\queueRunner.js:73:41
```

**Comment by alinanovof** [comment]
I was trying to debug it, and I realized the following error happens because the `rules` parameter is not defined in isStaticRules.js. So it fails on rules.length. Is there any fix or workaround? @kitten

**Comment by AaronV** [comment]
One of our tests was mocking `React.useContext` directly, and this seemed to be causing the .length error in that case.

I had to remove this:
```
    useContextMock = jest.fn();
    useContextMock.mockReturnValue(pagerContext);
    React.useContext = useContextMock;
```

**Comment by alinanovof** [comment]
@AaronV it works!! Thank you so much
