### ISSUE TITLE
Function createGlobalStyle don't work in esm and cjs bundles by wrong __SERVER__ global variables in build config

### ISSUE THREAD

**Issue by LabEG** [styled-components/styled-components#3714]
## Environment
Any clients side environment
### System:
 - OS: Windows 10 10.0.22000
 - CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
 - Memory: 12.25 GB / 31.91 GB
### Binaries:
 - Node: 17.3.1 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
 - npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
### npmPackages:
 - styled-components: =5.3.3 => 5.3.3

## Reproduction
Import node_modules\styled-components\dist\styled-components.cjs.js or node_modules\styled-components\dist\styled-components.cjs.js to client side code by any bundler.

## Steps to reproduce
```
import {createGlobalStyle} from "styled-components";
import styles from "./../../../../node_modules/swiper/swiper.min.css";

export const CssGlobalSwiper = createGlobalStyle`
    ${styles}
`;
```

## Expected Behavior
Insert global styles by bundles:
node_modules\styled-components\dist\styled-components.esm.js - work
node_modules\styled-components\dist\styled-components.cjs.js - work
node_modules\styled-components\dist\styled-components.js - work

## Actual Behavior
Insert global styles by bundles:
node_modules\styled-components\dist\styled-components.esm.js - don't work
node_modules\styled-components\dist\styled-components.cjs.js - don't work
node_modules\styled-components\dist\styled-components.js - work

## Where problem
In this line 
https://github.com/styled-components/styled-components/blob/main/packages/styled-components/src/constructors/createGlobalStyle.ts#L61
used variable `__SERVER__`. In rollup config this variable set to false for js bundle, and true for cjs and esm bundles. But its totaly wrong, because modern bundler can use cjs and esm for import script. CJS and ESM its not a version for nodejs, its versions for modern runtimes, also included a browsers.

## How fix it
Set variable `__SERVER__` in runtime, not a build time.

## Small improvement
In 2022 yeahr better way will dont make bundle, just transpile ts files to target es2015 and esnext modules.

## Rellated issue
https://github.com/styled-components/styled-components/issues/2670

**Comment by LabEG** [comment]
I can also make a pull request that will fix this error. If you wish.

**Comment by rbhalla** [comment]
@LabEG, are you using any workaround for this in the meanwhile?

I've been using:

```
import { createGlobalStyle } from 'styled-components/dist/styled-components';
```

It is fine, but I'm curious if there is something neater.

**Comment by LabEG** [comment]
At first, I did the same.
But then I made script in postinstall that replace entry point for module in package.json of styled components.

**Comment by Xiphe** [comment]
Can confirm that `createGlobalStyle` isn't working in client for `styled-components@>=5.3.1`

**Comment by drosenzweig** [comment]
I'm running into this same issue. Compiled with Vite, everything works fine in serve mode, but under a production build I get an error in the browser console:

```
Uncaught TypeError: ot is not a function
    at Qe (styled-components.browser.esm.js:1:15599)
    at vi (styled-components.browser.esm.js:1:22570)
    at GlobalStyles.js:8:22
```

This is with Vite 4.2.1, Node 16.18.0, tried with styled-components v5.3.0, 5.3.3, and 5.3.10.

**Comment by Xiphe** [comment]
On my end it turned out to be a misconfiguration, causing the server export of styled components to be loaded in the client.

**Comment by drosenzweig** [comment]
@Xiphe can you be a little more specific about what you misconfigured?

**Comment by Xiphe** [comment]
It was highly specific to my app, so I doubt it will be helpful. But nonetheless:

I had issues where esbuild (for some reason I don't remember) was not able to use the cjs build of  styled-components. So I was forcing it to use the esm build (by setting up an typescript alias, [might also happen with any other alias]). At that time I was not aware that styled components uses different runtimes on server and client so I accidentally forced all `import styled from 'styled-components'` to use the esm server bundle.

Currently I'm monkey-patching the package.json of styled-components to expose it's esm build for the server as `"main"` - this way client builds still go with the "browser" field.

Ideally this would be solved by fine-tuning the way the bundler imports this specific package instead of monkey patching, but in remix we don't have such granular settings.

**Comment by vilicvane** [comment]
Adding my use case here, I am working on a project that streams HTML rendering for Node.js CLI application, and expect styled-components to work with JSDOM as close as how it works in a browser.

And this `__SERVER__` hard-coded by compiler is kind of a blocker here. Also, there's a similar issue with `IS_BROWSER`. Though not hard-coded, but requires `import()` expression to delay the evaluation for ESM.

https://github.com/vilicvane/backpage/blob/ec0ec49f25b91d3b6e92f3d82a935342a0993145/src/examples/styled-components.tsx#L6-L15

I don't see notable benefit doing so instead of lazy evaluation.

**Comment by quantizor** [comment]
Closing — this issue is stale (2+ years without resolution) and relates to an older version of styled-components. If this is still reproducible on the latest v6.x release, please open a new issue with a minimal reproduction.
