### ISSUE TITLE
ThemeProvider fails render in browser: Uncaught Error: Cannot create styled-component for component: [object Object]

### ISSUE THREAD

**Issue by seanc-dev** [styled-components/styled-components#3742]
### System:
 - OS: macOS Mojave 10.14.6
 - CPU: (4) x64 Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz
 - Memory: 46.30 MB / 4.00 GB
 - Shell: 3.2.57 - /bin/bash
### Binaries:
 - Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
 - Yarn: 1.22.18 - /usr/local/bin/yarn
 - npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
### npmPackages:
 - styled-components: ^5.3.5 => 5.3.5 

## Steps to reproduce
Using Create React App 5.0.1, built a simple theme, added it through ThemeProvider in my index.js file and the project compiles correctly but then fails to render in browser. 

Stack trace for the console errors:
`Uncaught Error: Cannot create styled-component for component: [object Object].
    at j (error.js:30:1)
    at e (constructWithOptions.js:12:1)
    at He (styled.js:8:1)
    at renderWithHooks (react-dom.development.js:16175:1)
    at mountIndeterminateComponent (react-dom.development.js:20913:1)
    at beginWork (react-dom.development.js:22416:1)
    at beginWork$1 (react-dom.development.js:27381:1)
    at performUnitOfWork (react-dom.development.js:26513:1)
    at workLoopSync (react-dom.development.js:26422:1)
    at renderRootSync (react-dom.development.js:26390:1)`

Pulling my hair out on this as I'm pretty invested in styled-components in this project but the inability to add a theme renders it useless. Please advise.

My package json:

`{
  "name": "live-fully",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.2.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/styled-components": "^5.1.25",
    "postscribe": "^2.0.8",
    "react": "^18.1.0",
    "react-dom": "^18.1.0",
    "react-router-dom": "^6.3.0",
    "react-scripts": "5.0.1",
    "styled-components": "^5.3.5",
    "typescript": "^4.6.4",
    "web-vitals": "^2.1.4"
  },
  "engines": {
    "node": "16.15.0",
    "yarn": "1.22.18"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
`

**Comment by brucepouncey-qs** [comment]
I'm having a similar issue. I'm using Parcel, TS and React 18.2.0, styled-components 5.3.5 
`{
  "name": "Project",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@emotion/react": "^11.9.3",
    "@emotion/styled": "^11.9.3",
    "@mui/material": "^5.9.0",
    "esm": "^3.2.25",
    "normalize.css": "^8.0.1",
    "parcel": "^2.6.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "regenerator-runtime": "^0.13.9",
    "styled-components": "^5.3.5",
    "typescript": "^4.7.4"
  },
  "scripts": {
    "prebuild": "run-s clean",
    "build": "parcel build ./index.html --no-source-maps",
    "clean": "rimraf ./dist",
    "start": "parcel ./index.html --open"
  },
  "devDependencies": {
    "@types/node": "^18.0.3",
    "@types/react": "^18.0.15",
    "@types/react-dom": "^18.0.6",
    "@types/styled-components": "^5.1.25",
    "process": "^0.11.10"
  }
}`

Stack trace in console:
`index.js:1 The above error occurred in the <He> component:

    at He (http://localhost:1234/index.6fa4ea68.js:28615:6)
    at App (/__parcel_hmr/190901e123841a4f:29:50)
    at AppProvider (http://localhost:1234/index.6fa4ea68.js:27770:24)
`

`error.js:39 Uncaught Error: Cannot create styled-component for component: [object Object].
    at j (error.js:39:11)
    at e (constructWithOptions.js:15:12)
    at He (styled.js:8:33)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)
    at recoverFromConcurrentError (react-dom.development.js:25850:20)
    at performSyncWorkOnRoot (react-dom.development.js:26096:20)
    at flushSyncCallbacks (react-dom.development.js:12042:22)
    at flushSync (react-dom.development.js:26201:7)
    at Object.scheduleRoot (react-dom.development.js:27810:5)
    at react-refresh-runtime.development.js:280:17
    at Set.forEach (<anonymous>)
    at Object.performReactRefresh (react-refresh-runtime.development.js:259:25)
    at helpers.js:23:11
    at helpers.js:16:14`

@seanc-dev Did you find a solution ?

**Comment by judaihyun** [comment]
same issue.

i think, styled-component is not support react 18~

**Comment by quantizor** [comment]
Closing — this issue is stale (2+ years without resolution) and relates to an older version of styled-components. If this is still reproducible on the latest v6.x release, please open a new issue with a minimal reproduction.
