### ISSUE TITLE
Does Styled Components support NextJS 13 + Node 18

### ISSUE THREAD

**Issue by Msirkovsky** [styled-components/styled-components#3990]
Hi,

I'm wondering if the Styled Components supports NextJS 13 + Node 18. I am using the latest version of NextJS(13), React 18 and the Styled component version 5.3.9 and Node v18.13.0. And the simple page with one component returns the following error:

```
error - Error [TypeError]: Cannot read properties of null (reading 'useState')
    at Object.useState (c:\my_project\node_modules\react\cjs\react.development.js:1622:21)
    at ae (c:\my_project\node_modules\styled-components\dist\styled-components.cjs.js:1:13271)
    at renderWithHooks (c:\my_project\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5658:16)
    at renderIndeterminateComponent (c:\my_project\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5731:15)
    at renderElement (c:\my_project\node_modules\react-dom\cjs\react-dom-server.browser.development.js:5946:7)
```

But when I switch to Node version 16.15.0, everything works. 

Thanks in advance for any input/advice.

**Comment by probablyup** [comment]
Did you follow this? https://beta.nextjs.org/docs/styling/css-in-js#styled-components

**Comment by Msirkovsky** [comment]
> Did you follow this? https://beta.nextjs.org/docs/styling/css-in-js#styled-components

No, I didn't because I don't use the new App router(beta). I am using the stable one(_pages folder_)

**Comment by ronker-bump** [comment]
It's a pathetic experience if you are working with a custom styled component package and trying to use it with nextjs.

**Comment by Msirkovsky** [comment]
Ok, the problem is in the Windows terminal. It works when I run it via PowerShell.
