### ISSUE TITLE
NPM install fails with 'edgesout' warning

### ISSUE THREAD

**Issue by baufometic** [styled-components/styled-components#3998]
Node 18.15.0
NPM 9.6.7
Ubuntu Linux
VS Code
Regular Next JS project

Install works fine with an older version of SC i.e. npm i styled-components@5.3.1
Installed SC a few hours ago in a copy of this repo, so it must be the latest release.

## Steps to reproduce
npm i styled-components

**Comment by ossio99** [comment]
It isn't working yet

**Comment by Leekwanghoon** [comment]
i have the same issue.
let try yarn

yarn add styled-components

**Comment by Sambhav399** [comment]
It's having an issue. I tried with upgrading and downgrading node and npm versions it always shows an error.

To Fix this use specifically 5.3.10 version of styled-components

For projects using JS/JSX(JavaScript)
`npm i -D styled-components@5.3.10`

For projects using TS/TSX(TypeScript)
`npm i -D styled-components@5.3.10 @types/styled-components`

**Comment by nirzafran** [comment]
> It's having an issue. I tried with upgrading and downgrading node and npm versions it always shows an error.
> 
> To Fix this use specifically 5.3.10 version of styled-components
> 
> For projects using JS/JSX(JavaScript) `npm i -D styled-components@5.3.10`
> 
> For projects using TS/TSX(TypeScript) `npm i -D styled-components@5.3.10 @types/styled-components`

thx!

**Comment by dougfbf** [comment]
I was having the same issue.
It worked when I tried `npm install styled-components@latest` .

**Comment by dougfbf** [comment]
I was having the same issue.
It worked when I tried the following: `npm install styled-components@latest`

**Comment by CodyMan0** [comment]
Thanks~ I was having the same issue as well!

**Comment by MiRoro2** [comment]
i was having the same problem... thanks!

**Comment by kode-neko** [comment]
Hello Everyone! ✋

Phew... I'm not the only one with this problem. For the moment the only and secure solution is use a previous version. In my case y decided to downgrade `@5.3.10`. When the new version 6 is stable, I will use it.

```shell
npm install "styled-components@5.3.10"
```

It could be usefull publish the output terminal 💻

```shell
$ npm install styled-components
npm ERR! Cannot read properties of null (reading 'edgesOut')

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\koden\AppData\Local\npm-cache\_logs\2023-05-08T12_55_24_726Z-debug-0.log
```

Have a nice day!

**Comment by CodePhilanthropist** [comment]
### Solution for styled-components installation issue (v6.0.0-rc.1)

Hello everyone,

If you have encountered issues installing styled-components recently, it might be due to the newly published unstable version 6.0.0-rc.1, published [2 days ago](https://www.npmjs.com/package/styled-components?activeTab=versions). Here's the solution to this problem.

To install the latest unstable version (v6.0.0-rc.1) of styled-components, run the following command:
`npm install styled-components@latest`

However, if you prefer to use a stable version (v5.x.x) instead of the unstable version, you can install it using the following command:
`npm install styled-components@5`
This will ensure you're using the stable version 5 of styled-components and avoid potential issues related to the unstable release.

**Comment by deniyaldanidan** [comment]
I'm having same issue. `npm i styled-components` doesnt work. but `npm i styled-components@5` works. 

Thanks.

**Comment by shazinet** [comment]
> It's having an issue. I tried with upgrading and downgrading node and npm versions it always shows an error.
> 
> To Fix this use latest LTS v5.3.10 version of styled-components
> 
> For projects using JS/JSX(JavaScript) `npm i -D styled-components@5.3.10`
> 
> For projects using TS/TSX(TypeScript) `npm i -D styled-components@5.3.10 @types/styled-components`

What about using latest keyword instead of using the exact version?

**Comment by Sambhav399** [comment]
> > It's having an issue. I tried with upgrading and downgrading node and npm versions it always shows an error.
> > To Fix this use latest LTS v5.3.10 version of styled-components
> > For projects using JS/JSX(JavaScript) `npm i -D styled-components@5.3.10`
> > For projects using TS/TSX(TypeScript) `npm i -D styled-components@5.3.10 @types/styled-components`
> 
> What about using **latest** keyword instead of using the exact version? `npm i -D styled-components@latest`

At the time of that comment it was latest LTS version. So I mentioned it

**Comment by mitranjaykrishna** [comment]
Yh  same using this it solved
` npm install styled-components@latest`

**Comment by mohamuhsin** [comment]
got solved by  npm install styled-components@latest, shukran.

**Comment by jelmd** [comment]
According to the log it seems npm is broken, not?
```
72 timing command:update Completed in 627ms
73 verbose stack TypeError: Cannot read properties of null (reading 'edgesOut')
73 verbose stack     at [loadPeerSet] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1307:38)
73 verbose stack     at async [loadPeerSet] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1315:11)
73 verbose stack     at async [buildDepStep] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:929:11)
73 verbose stack     at async Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:207:7)
73 verbose stack     at async Promise.all (index 1)
73 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
73 verbose stack     at async Update.exec (/usr/lib/node_modules/npm/lib/commands/update.js:64:5)
73 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli.js:134:5)
74 verbose cwd ...
```

**Comment by deepbodo** [comment]
Thanks u saved me! I felt useless without it

**Comment by DavonWhitworth** [comment]
> I was having the same issue. It worked when I tried the following: `npm install styled-components@latest`

This worked for me. Thanks

**Comment by IskraI** [comment]
Thanks you helped me!

**Comment by fresonn** [comment]
Just use: ```npm i styled-components@5```

**Comment by chaitanya-000** [comment]
None of the above solutions worked for me. 
Tried - `npm install styled-components@5 --force`.
It worked. 
But make sure that you make a test styled component and create a build as soon as you use this. Chances are it may work during development but may crash in build or production

**Comment by wizzy-design** [comment]
Phew, thanks for all the solutions guys

**Comment by haneenmahd** [comment]
I faced the same issue with my Next 13 project.

But I could install it successfully by running:
```
npm i styled-components@latest
```

**Comment by george-thomas-hill** [comment]
Subscribing.

**Comment by jelmd** [comment]
Because my project does __not__ depend on `styled-components`, I prefer to patch the bogus npm (Q&D):
```patch
--- /usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js.orig	2023-04-12 05:45:24.000000000 +0200
+++ /usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js	2023-05-24 18:15:49.699840640 +0200
@@ -1304,6 +1304,11 @@
         continue
       }
 
+		var x = node.parent.edgesOut.get(edge.name);
+		//console.log('\nedge.name=\n', edge.name, '\n', x );
+		if (!x)
+			continue;
+
       const parentEdge = node.parent.edgesOut.get(edge.name)
       const { isProjectRoot, isWorkspace } = node.parent.sourceReference
       const isMine = isProjectRoot || isWorkspace
```

**Comment by quantizor** [comment]
Closing — this issue is stale and likely resolved in newer releases. If still reproducible on the latest v6.x, please open a new issue.
