### ISSUE TITLE
Changing document.title throws the error "Cannot find a StyleSheet instance"

### ISSUE THREAD

**Issue by Msirkovsky** [styled-components/styled-components#4040]
Hi all,

it's super weird but when I use this code:
```
document.title = "any string";
```
and then rerender any component, it causes the following error:

```
Error: An error occurred. See https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/utils/errors.md#10 for more information.
    at new e (2.b5a40e5c.chunk.js:1:127816)
    at $ (2.b5a40e5c.chunk.js:1:129595)
    at Object.insertRules (2.b5a40e5c.chunk.js:1:132663)
    at t.inject (2.b5a40e5c.chunk.js:1:136095)
    at t.generateAndInjectStyles (2.b5a40e5c.chunk.js:1:139513)
    at e.generateAndInjectStyles (2.b5a40e5c.chunk.js:1:144292)
    at e.renderInner (2.b5a40e5c.chunk.js:1:143248)
    at Rs (2.b5a40e5c.chunk.js:1:2097342)
    at Pc (2.b5a40e5c.chunk.js:1:2079580)
    at Sc (2.b5a40e5c.chunk.js:1:2079505)
```

I'm using CRA and styled-components v. 4.4.1.

I've also noticed that the styled-components adds the element `style` into the title attribute in the head section.
```
<head>
<title>Test<style data-styled="" data-styled-version="4.4.1">
/* sc-component-id: sc-bwzfXH */
...
</style></title>
...
```

Thanks.

**Comment by usercao** [comment]
Why not upgrade to version 6.0 and try again? This may be caused by an older version.

**Comment by lordvic4real** [comment]
I will like to work on this issue

**Comment by lordvic4real** [comment]
> Why not upgrade to version 6.0 and try again? This may be caused by an older version.

You have a good point

**Comment by Msirkovsky** [comment]
Hi, I've upgraded to v5.3.11 and the issue still persists. 
![image](https://github.com/styled-components/styled-components/assets/6298851/5d3ad6fa-0263-42c9-8e11-8b29f0062ab8)

**Comment by probablyup** [comment]
Should be fixed in https://github.com/styled-components/styled-components/releases/tag/v6.0.0-rc.6, thanks for using styled-components!
