### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'Text')

### ISSUE THREAD

**Issue by mjstelly** [styled-components/styled-components#4164]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown`
## System:
 - OS: macOS 13.2.1
 - CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
 - Memory: 518.91 MB / 16.00 GB
 - Shell: 5.8.1 - /bin/zsh
## Binaries:
 - Node: 16.20.1 - ~/.nvm/versions/node/v16.20.1/bin/node
 - Yarn: 3.6.1 - ~/.nvm/versions/node/v16.20.1/bin/yarn
 - npm: 8.19.4 - ~/.nvm/versions/node/v16.20.1/bin/npm
 - Watchman: 2023.07.24.00 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^2.1.4 => 2.1.4
 - styled-components: ^6.0.4 => 6.0.7
 
## Reproduction
First off, `styled-components` work as intended in the app. This issue pertains ONLY to the conflict with the testing libraries.

My `App.tsx` imports `ThemeProvider` and theme controller file `MainTheme`.
```
import {ThemeProvider} from 'styled-components/native';
import {MainTheme} from '@themes/MainTheme';

<ThemeProvider theme={MainTheme}>
```
In turn, `MainTheme` imports all the separate theme files
```
import {lightTheme} from '@themes/Colors';
import {TypographyStyles} from '@themes/Typography';
import {StyledComponents} from '@themes/StyledComponents';

export const MainTheme = {
  ...lightTheme,
  ...TypographyStyles,
  ...StyledComponents,
};
```
and exports the unified component which is consumed through `useTheme()`.

PlainTextBold in Typography
```
const PlainTextBold = styled.Text`
  ${commonTextStyle('15', 'oxford', 'bold')}
`;
```
Example of theme being called.
```
import {useTheme} from 'styled-components/native';
const {PlainTextBold} = useTheme();
... JSX
<PlainTextBold>{getInitials(userName)}</PlainTextBold>
```
`App.test.tsx` is one simple test
```
import React from 'react';
import {render} from '@testing-library/react-native';
import App from '@src/App';

describe('App', () => {
  it('renders without crashing', () => {
    render(<App />);
  });

  // Add more test cases as needed
});
```
It fails everytime at
```
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'Text')

      39 | // `;
      40 |
    > 41 | const PlainTextBold = styled.Text`
         |                              ^
      42 |   ${commonTextStyle('15', 'oxford', 'bold')}
      43 | `;
      44 |

      at Object.Text (src/ui/themes/Typography.ts:41:30)
      at Object.require (src/ui/themes/MainTheme.ts:2:1)
...
```
It doesn't matter if I use `styled(Text)` or `styled.Text`; or `import styled` or `import {styled}`, the results are the same.

## Expected Behavior
I expect the test to pass.

## Actual Behavior
The test fails with the error listed above.

**Comment by SherifNeamatalla** [comment]
Any news on this?

**Comment by quantizor** [comment]
Closing — this issue is stale and relates to an older version. If still reproducible on the latest v6.3.x release, please open a new issue with a minimal reproduction.
