### ISSUE TITLE
Typescript typing errors

### ISSUE THREAD

**Issue by chuson1996** [styled-components/styled-components#928]
I have this error while running tslint in a react, typescript project. But the weird thing about it is that if I use my global tslint command then it's okay but if I use a internal tslint I installed in my project then there're these errors.

(styled-components v2)
```
Error at node_modules/styled-components/typings/styled-components.d.ts:23:52: Generic type 'StyledComponentClass<P, T, O>' requires 3 type argument(s).
Error at node_modules/styled-components/typings/styled-components.d.ts:33:47: ',' expected.
Error at node_modules/styled-components/typings/styled-components.d.ts:33:49: Duplicate identifier 'P'.
Error at node_modules/styled-components/typings/styled-components.d.ts:41:47: ',' expected.
Error at node_modules/styled-components/typings/styled-components.d.ts:41:49: Duplicate identifier 'P'.
Error at node_modules/styled-components/typings/styled-components.d.ts:44:37: ',' expected.
Error at node_modules/styled-components/typings/styled-components.d.ts:44:39: '>' expected.
Error at node_modules/styled-components/typings/styled-components.d.ts:44:41: Expression expected.
Error at node_modules/styled-components/typings/styled-components.d.ts:44:43: Cannot find name 'attrs'.
Error at node_modules/styled-components/typings/styled-components.d.ts:44:48: ')' expected.
Error at node_modules/styled-components/typings/styled-components.d.ts:44:50: 'Attrs' only refers to a type, but is being used as a value here.
Error at node_modules/styled-components/typings/styled-components.d.ts:44:68: '(' expected.
Error at node_modules/styled-components/typings/styled-components.d.ts:44:69: ';' expected.
Error at node_modules/styled-components/typings/styled-components.d.ts:44:71: 'ThemedStyledFunction' only refers to a type, but is being used as a value here.
Error at node_modules/styled-components/typings/styled-components.d.ts:44:112: '(' expected.
Error at node_modules/styled-components/typings/styled-components.d.ts:45:1: Declaration or statement expected.
Error at node_modules/styled-components/typings/styled-components.d.ts:47:33: Generic type 'ThemedStyledFunction<P, T, O>' requires 3 type argument(s).
Error at node_modules/styled-components/typings/styled-components.d.ts:49:46: Generic type 'ThemedStyledFunction<P, T, O>' requires 3 type argument(s).
Error at node_modules/styled-components/typings/styled-components.d.ts:52:64: Generic type 'ThemedStyledFunction<P, T, O>' requires 3 type argument(s).
Error at node_modules/styled-components/typings/styled-components.d.ts:66:33: Generic type 'ThemedStyledFunction<P, T, O>' requires 3 type argument(s).
```

**Comment by marvinhagemeister** [comment]
Curious: which typescript version are you using?

**Comment by chuson1996** [comment]
@marvinhagemeister tslint 5.4.3 typescript 2.2.1

**Comment by patrick91** [comment]
@chuson1996 can you try with TS 2.3? I'll check if there's any issue in the meanwhile

**Comment by chuson1996** [comment]
@patrick91 upgrading typescript to 2.3 fix the bug. Thanks.
